POST https://fullstacktarefa2.onrender.com/tarefas
Content-Type: application/json

{
  "titulo": "Tarefa: Dominar Tudo",
  "descricao": "Criar um CRUD basico usando Express",
  "deadline": "2025-12-31",
  "prioridade": "alta"
}

###

GET https://fullstacktarefa2.onrender.com/tarefas

###

PUT https://fullstacktarefa2.onrender.com/tarefas/8871220c-61f5-45e5-9e04-2d8d613706cb
Content-Type: application/json

{
  "titulo": "Tarefa: Deploy do CRUD com sucesso",
  "descricao": "Aprender a criar um CRUD mediano usando Express",
  "deadline": "2025-12-31",
  "prioridade": "alta"
}

###

DELETE https://fullstacktarefa2.onrender.com/tarefas/d3259704-2166-4d6d-b69b-bac23162cd34